# Generated by Django 3.2.12 on 2022-03-20 14:18

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Special Access')


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
