# Generated by Django 3.2.12 on 2022-03-14 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_boys', models.IntegerField()),
                ('num_of_girls', models.IntegerField()),
                ('leader_name', models.CharField(max_length=50)),
                ('leader_contact_num', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('college_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
