# Generated by Django 3.2.7 on 2022-03-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameName',
            new_name='name',
        ),
    ]
