# Generated by Django 3.2.12 on 2022-03-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teams', '0002_contingent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingent',
            name='id',
        ),
        migrations.AlterField(
            model_name='contingent',
            name='college_rep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
