# Generated by Django 3.2.12 on 2022-03-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20220314_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='num_of_officials',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
