# Generated by Django 3.2.7 on 2022-03-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Authentication', '0002_useraccount_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
