# Generated by Django 3.2.7 on 2022-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_useraccount_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
